/* Generated by incbin */

#include <stddef.h>

CHIP const unsigned char ball2bpl16x16_frame1_palette_data[] = {
/*00000000*/ 0x00,0x0f,0x0e,0xdd,0x09,0x22,0x0b,0x77
};

const size_t ball2bpl16x16_frame1_palette_size = sizeof(ball2bpl16x16_frame1_palette_data);
