/* Generated by incbin */

#include <stddef.h>

CHIP const unsigned char g_tBalllPalette_data[] = {
/*00000000*/ 0x00,0x0f,0x0e,0xdd,0x09,0x22,0x0b,0x77
};

const size_t g_tBalllPalette_size = sizeof(g_tBalllPalette_data);
